baseURL: "https://vijayabharathib.github.io/beehive_hugo_theme/"
languageCode: "en-us"
title: "Beehive Hugo Theme"
theme: "beehive"
publishDir: "docs"
canonifyURLs: true
paginate: 2
params:
  description: "Lean hugo theme for easy publishing"
  subtitle: "Lean hugo theme for easy publishing"

author:
  vijayabharathib:
    firstname: "Vijayabharathi"
    lastname: "Balasubramanian"
    bio: "All over the world in 80 days"
    social:
      website: "https://vijayabharathi.in"
      twitter: "vijayabharathib"
      github: "vijayabharathib"
