baseURL: "https://vijayabharathib.github.io/beehive_hugo_theme/"
languageCode: "en-us"
title: "My New Hugo Site"
theme: "beehive"
publishDir: "docs"

author:
  vijayabharathib:
    firstname: "Vijayabharathi"
    lastname: "Balasubramanian"
    bio: "All over the world in 80 days"
    social:
      website: "https://vijayabharathi.in"
      twitter: "vijayabharathib"
      github: "vijayabharathib"
