baseURL: "https://beehive.netlify.com/"
languageCode: "en-us"
title: "Beehive Hugo Theme"
theme: "beehive"
publishDir: "docs"
canonifyURLs: true
paginate: 2
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsUseClassic: true
menu:
  main:
      - Name: "about"
        Identifier: "about"
        URL: "/page/about/"
        weight: 220
      - Name: "privacy"
        Identifier: "privacy"
        URL: "/page/privacy/"
        weight: 110
categories: [
  "HTML",
  "CSS",
  "Javascript",
  "Service Workers",
  "Progressive Web App",
  "React",
  "Test Automation",
  "Web Design",
  "Responsive Design",
  "DevOps",
  "Rails",
  "Docker"
]
params:
  description: "Lean hugo theme for easy publishing"
  subtitle: "Lean hugo theme for easy publishing"
  analytics: "https://unarstaged.herokuapp.com/visits"
  
author:
  vijayabharathib:
    firstname: "Vijayabharathi"
    lastname: "Balasubramanian"
    bio: "All over the world in 80 days"
    social:
      website: "https://vijayabharathi.in"
      twitter: "vijayabharathib"
      github: "vijayabharathib"
