version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: hugo server --disableLiveReload -wvFD --bind=0.0.0.0
    volumes:
      - .:/usr/share/blog
    ports:
      - "1313:1313"
