version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: hugo server -wvFD --bind=0.0.0.0
    volumes:
      - .:/usr/share/blog
      - /usr/share/blog/node_modules
    ports:
      - "1313:1313"
