name = "Beehive"
license = "MIT"
licenselink = "https://github.com/vijayabharathib/beehive_hugo_theme/blob/master/LICENSE.md"
description = "Dark blog theme extracted from pineboat.in"
homepage = "http://beehive.netlify.com/"
tags = ["blog","PWA"]
features = ["Offline content","Progressive Web App"]
min_version = "0.47"

[author]
  name = "Vijayabharathi"
  homepage = "https://www.vijayabharathi.in"

