baseURL: "https://beehive.netlify.com/"
languageCode: "en-us"
title: "Beehive Hugo Theme"
theme: "beehive"
themesDir: "../.."
paginate: 2
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsUseClassic: false
canonifyUrls: false

menu:
  main:
      - Name: "Home"
        URL: "/"
        weight: 101
      - Name: "About"
        URL: "/page/about/"
        weight: 220
      - Name: "Search"
        URL: "/page/search/"
        weight: 333
categories: [
  "HTML",
  "CSS",
  "Javascript",
  "Service Workers",
  "Progressive Web App",
  "React",
  "Test Automation",
  "Web Design",
  "Responsive Design",
  "DevOps",
  "Rails",
  "Docker"
]
params:
  description: "Lean hugo theme for easy publishing"
  subtitle: "Lean hugo theme for easy publishing"
  analytics: "http://localhost:3000/visits"
  algolia: 
    vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
    params = ["categories", "tags"]
author:
  vijayabharathib:
    firstname: "Vijayabharathi"
    lastname: "Balasubramanian"
    bio: "All over the world in 80 days"
    social:
      website: "https://vijayabharathi.in"
      twitter: "vijayabharathib"
      github: "vijayabharathib"

related:
  threshold: 80
  includeNewer: true
  indices:
    - name: categories 
      weight: 200
    - name: tags
      weight: 100
    - name: date
      weight: 10

outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true

outputs:
  home: 
    - HTML
    - RSS 
    - Algolia
    
